#!/bin/sh
set -e
qcow2_disk_size="32G"
while [ $# -gt 0 ]; do
case "$1" in
-size) shift; qcow2_disk_size="$1";;
*) break;;
esac
shift
done
mkdir -p "$out_meta_os_ntux_stable_amd_amd64_img_full_dir"
qemu-img create -f qcow2 "$out_meta_os_ntux_stable_amd_amd64_img_full_dir$meta_ntux_stable_amd_amd64_qcow2_disk" "$qcow2_disk_size" "$@"
