#!/bin/sh
set -e
display_help() { printf "\n Usage: $0 [options]\n\n Args:\n  --help          | Show this help message and exit\n\n  -d <dev>        | Write image to device\n  -b <block size> | Block size (default 4M)\n  -sync           | Check writted after write to device (default false)\n\n"; exit 0; }
dev="" bs="4M" sync_enabled=false
while [ $# -gt 0 ]; do
    case "$1" in
        -d) dev="$2"; shift 2 ;;
        -b) bs="$2"; shift 2 ;;
        -sync) sync_enabled=true; shift ;;
        --help) display_help ;;
        *) printf "\n dd_img: unknown arg: $1\n Try --help for more info\n\n"; exit 1 ;;
    esac
done
if [ -z "$dev" ]; then printf "\n dd_img: device not specified: dev /dev/sda\n Try --help for more info\n\n"; exit 0; fi
dd if="$out_meta_os_ntux_stable_amd_amd64_img_full_dir$meta_ntux_stable_amd_amd64_iso" of="$dev" bs="$bs" status=progress
[ "$sync_enabled" = true ] && sync
