#!/bin/sh
set -e
display_help(){ printf "\n Usage: $0 [options]\n\n Args:\n  --help | Show this help message and exit\n\n Any other options will be passed to qemu-system-x86_64\n example: qemu -enable-kvm\n\n"; exit 0; }
for a in "$@"; do
[ "$a" = --help ] && display_help
done
mkdir -p "$out_meta_os_ntux_stable_amd_amd64_img_full_dir"
qemu-system-x86_64 -nographic -m 4G -smp 2 -boot order=cd -cpu host -cdrom "$out_meta_os_ntux_stable_amd_amd64_img_full_dir$meta_ntux_stable_amd_amd64_iso" -drive file="$out_meta_os_ntux_stable_amd_amd64_img_full_dir$meta_ntux_stable_amd_amd64_qcow2_disk",format=qcow2,if=virtio "$@"
