#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2027, Kolya

# Stop script on error
set -e

# Display help fn
display_help() {
	printf "\n Usage: $0 [options]\n"
	printf "\n Args:\n"
	printf "  --help | Show this help message and exit\n\n"
	printf " Any other options will be passed to qemu-system-x86_64\n"
	printf " example: qemu -enable-kvm\n\n"
	exit 0
}

# Arg handler
for arg in "$@"; do
	case "$arg" in
		--help)
			display_help
			;;
	esac
done

# Create dirs
mkdir -p "$out_meta_os_ntux_stable_amd_amd64_img_full_dir"

# Run ntux-stable-amd-amd64 img
qemu-system-x86_64 \
	-nographic \
	-m 4G \
	-smp 2 \
	-boot order=cd \
	-cpu host \
	-cdrom "$out_meta_os_ntux_stable_amd_amd64_img_full_dir$meta_ntux_stable_amd_amd64_iso" \
	-drive file="$out_meta_os_ntux_stable_amd_amd64_img_full_dir$meta_ntux_stable_amd_amd64_qcow2_disk",format=qcow2,if=virtio \
	"$@"
